###
GET http://localhost:3000/api/clientes HTTP/1.1

###
GET http://localhost:3000/api/clientes/638d1d5fac46ef3930e020d3 HTTP/1.1

###
POST http://localhost:3000/api/clientes HTTP/1.1
Content-Type: application/json

{
        "Tipo": "Cedula Ciudadania",
        "Nombre": "Maria Alejandra",
        "Apellido": "Rivera Sarez",
        "Edad": 21,
        "Sexo": "Femenino",
        "Correo": "alejamar21@outlook.com",
        "Telefono": 3112147589,
        "Direccion": "Cra 4 C 2 Ac 32"
}

###
PUT http://localhost:3000/api/clientes/638d1d5fac46ef3930e020db HTTP/1.1
Content-Type: application/json

{
    "Correo": "vanemiranda345@outlook.com",
    "Telefono": 3112569874,
    "Direccion": "Cra 7 C 84 Sur 32"
}




###
GET http://localhost:3000/api/celulares HTTP/1.1

###
GET http://localhost:3000/api/celulares/638d1e40ac46ef3930e15f25 HTTP/1.1

###
POST http://localhost:3000/api/celulares HTTP/1.1
Content-Type: application/json

{
        "Nombre": "SAMSUNG GALAXY NOTE 9",
        "Marca": "SAMSUNG",
        "Modelo": "2022",
        "Memoria": "6 GB",
        "Almacenamiento": "128 GB",
        "Red": "5G"
}

###
PUT http://localhost:3000/api/celulares/638d1e40ac46ef3930e15f27 HTTP/1.1
Content-Type: application/json

{
   "Modelo": "2023",
    "Memoria": "8 GB",
    "Almacenamiento": "64 GB"
}




###
GET http://localhost:3000/api/ventas HTTP/1.1

###
GET http://localhost:3000/api/ventas/638d1de1ac46ef3930e0e319 HTTP/1.1

###
POST http://localhost:3000/api/ventas HTTP/1.1
Content-Type: application/json

{
        "_idCelular": 11,
        "_idCliente": 1078961425,
        "Fecha": "new Date(2022-12-05)",
        "Detalle": "1 unidad vendida, color purpura lavanda",
        "Precio": 2000000
}

###
PUT http://localhost:3000/api/ventas/638d1de1ac46ef3930e0e31b HTTP/1.1
Content-Type: application/json

{
    "Detalle": "1 unidad vendida, color azul marino",
    "Precio": 2525000
}